services:
    Olivier127\PlaceHolderGenerator\:
        autowire: true
        autoconfigure: true
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
